### ISSUE TITLE
can't get audio to work

### ISSUE THREAD

**Issue by autumncheney** [stargateaudio/stargate#28]
**Describe the bug**
after i built stargate from source, i can't get any audio to work. when i press play, the transport doesn't do anything. i selected jack as my host api and pulseaudio jack source as the audio device

**To Reproduce**
i was trying to use the va1 synth, but i can't get audio out of it

**Expected behavior**
i expect to hear audio and the transport to function

**Screenshots**

**Hardware and operating system**
ubuntu studio 20.10, jack, system76 gazelle w/ 16 x i7-10870h cpu, 16 gb of ram

**Additional context**
i built stargate from source

**Comment by stargateaudio** [comment]
Hello @autumncheney ,

Thanks for reporting this issue.  Most likely the device you chose is not active on your system.  That is almost always the cause of no-audio/playback-cursor-does-not-move.  Obviously not  a good user experience, I will write some documentation about how to troubleshoot this, and maybe some code to detect when it is happening and guide the user.  (or maybe some code to detect which devices are not active before generating the device list, if feasible).

What other choices did you have for Jack devices?  You can get back to the hardware dialog from:
```
Main Menu(button on the upper left)->File->Hardware Settings...
```
I have not used Ubuntu Studio, I am not sure if they automatically start a Jack server, you may need to start Jack first before selecting a device in Stargate.  Alternately, you could try stopping Jack and selecting your soundcard directly using ALSA, which should definitely work.

**Comment by autumncheney** [comment]
the only other audio device available under jack was "system". i did select alsa and one of my sound cards, and i was able to get the playhead to move when i press the play button, but i still don't hear any audio, even after turning off my jack server

**Comment by autumncheney** [comment]
alright, i tried exporting a project, the audio works there, just actually playing audio in the daw doesn't work

**Comment by stargateaudio** [comment]
For Jack, it is more likely that `system` is the correct device, and not `pulseaudio`.

As for the ALSA back end not making sound, there are a few of potential causes:
1. You selected a different device than the one that is actually connected to your speakers.  For example, you chose `HDMI`, when your speakers are connected to the `Analog` output.
2. Your device volume is turned down.  Try turning it up using whatever system volume widget your distro provides, or you can install `alsamixer` (`sudo apt install alsa-utils`) and run it from the terminal to select your soundcard and turn up the volume.
3. (less likely) something else is already using the device, such as your web browser having Youtube videos open, or the Jack daemon, etc...  But if this was happening, I would not expect the playback cursor to move

Are you using the internal soundcard on your laptop?  Or a USB soundcard, USB headphones, or something else?

**Comment by autumncheney** [comment]
i got it to work! i had to go to my pulseaudio settings and enable the "add virtual output device" checkbox, and that made the analog output appear in stargate

thx for your help! i'm just using pulseaudio for now, but i'll see if i can get jack to work

**Comment by stargateaudio** [comment]
Great! I hope you enjoy it.
