### ISSUE TITLE
Portable Mode

### ISSUE THREAD

**Issue by MrTeeXD** [stargateaudio/stargate#39]
**Briefly describe your usage of Stargate**
Hey there, I saw your project got mentioned in a Youtuber's RocketChat and I got interested and wanted to try it out for myself. However, I am currently lending a PC and I am using Portable Versions of Software I use on a daily basis.

**Describe what you want to do**
I want to be able to take Stargate DAW everywhere I go

After the high-level overview statement, you may provide additional detail and
context below.

**Does your proposal align with the core project design principles?**
It seems as if your Proposal.md is missing from this Repo but I do believe it align's with the proposal. Why did I request this? Well, I have seen alot of people wanted to use software when borrowing other PC's but are not allowed to install 3rd Party Programs, this Portable Feature may help remove some of those boundries and help others use this software 

**OPTIONAL: Describe one or more ways you propose we can accomplish this**
I heard that a website called https://portapps.io/ uses a sepcial wrapper that makes any application into a zippable package, allowing for ease of installing and usage.

**Additional context**
I will understand if this is not planned and that this issue will be closed. You don't have to make this a feature if its not needed in any way.

I do own a Odysee Channel where I use it to test new softwares and can allow me to provide live feedback to devs on how to imrpove their products like I have done a few months ago.

**Comment by stargateaudio** [comment]
Hello, thanks for the feature request.  The current Windows .exe file is portable, it can be run from any computer without installing, just carry the .exe on a flash drive and run it anywhere.  

Stargate can also store all of your projects, samples and settings on the flash drive using [these instructions](https://github.com/stargateaudio/stargate/blob/main/docs/windows_portable_flash_drive.md).  Please note that I actually do all Windows porting and testing in a VM, I have never tested this on a physical Windows installation.  If you find any bugs or issues, please report them, I am eager to make this feature work well.

I was not familiar with Portapps before you shared it here, as far as I can tell, the above mentioned features already do everything that Portapps would do?  If there is additional value to using Portapps that I missed, please let me know.

**Comment by stargateaudio** [comment]
As a side note:  I actually have a TODO item to create a non-portable installer for people who would want that, but I am not sure when I will have time to get to that.  Trust me, I worked very hard to make Stargate truly useful as a portable exe on Windows, that was a very important feature  :-)

**Comment by stargateaudio** [comment]
Also, if you are interested in reviewing Stargate on your channel or any other media, I am happy to help you.  Please note that the project is currently unannounced, I do not consider it to be a finished product yet.  Might take one more month or so to finish it and announce it publicly.  I was surprised that it has received this much attention already, considering that I did not advertise it anywhere yet.

You can email me at stargate.audio.github (a) gmail dot com to discuss further.

**Comment by stargateaudio** [comment]
I have not heard back from you, I am going to assume that the existing portable exe functionality meets your needs and close the ticket.  If this is incorrect, we can reopen this ticket, or submit new tickets to fix or enhance the portable executable functionality.

Side note:  The next release will feature 2 Windows binaries, the portable executable, and a proper installer.  They will be clearly labelled as such.  In the future, they may be merged into the installer, which may offer options to install to a flash drive, also using the flash drive for settings and sample storage.  We may also offer a live Linux USB image for portable use in the future.

**Comment by MrTeeXD** [comment]
Hello there, my biggest apologies, I was trying to make the Portable Functionaily work and was testing throroughly and of course I will reopen when I have some enhancments on my mind. :)

**Comment by stargateaudio** [comment]
No worries.  Like I said, I am eager to make Stargate the best portable DAW, very interested in your feedback on the portable experience (and anything else).

 I'm actually working on merging the installer and portable executable right now, which should make for a seamless and intuitive user experience, without having to manually setup a flash drive.  So maybe the release this weekend will feature that functionality in a single exe, assuming I can make it all work.

I might also reach out to Portapps about having them package it closer to the 1.0 release in a month or so, I could offer to buy them the code signing cert they want to expedite the process.

**Comment by MrTeeXD** [comment]
Sounds amazing! Also, you might want to fix that Proposal.md as it appears to be missing. But other then that, I am looking forward to what you are bringing into Stargate :D

**Comment by stargateaudio** [comment]
> Also, you might want to fix that Proposal.md as it appears to be missing
Should already be fixed.

Update:  There will now be an option to do a `Portable Flash Drive Install` in the Windows installer, so the Windows binaries will be unified in the next release, and it will also be possible (for the first time) to do a proper system install.

I did notice a small issue when I was testing right now, file browser bookmarks will need to use a relative path to the Stargate user folder when running in portable mode, otherwise the bookmarks will break if the drive letter for the flash drive changes.  Should be easy, will try to fix that today before I release again this weekend.

**Comment by MrTeeXD** [comment]
Sounds good! Im excited for the next release

**Comment by stargateaudio** [comment]
Fixed the bookmarks issue.  The portable experience should be excellent in the next release.

Currently testing and waiting for my graphics designer to deliver some SVG+CSS assets (this update will bring some massive UI changes, especially to plugins).  Will release `21.09.2` on Monday at the latest.

**Comment by MrTeeXD** [comment]
Exciting!!

**Comment by stargateaudio** [comment]
The new Windows installer with the portable install option [can be downloaded here](https://github.com/stargateaudio/stargate/releases/download/release-21.09.2/stargate-21.09.2-win64-installer.exe)

Also, if you want to discuss the portable features further, feel free to move the conversation [to the new Stargate Discord channel](https://discord.com/channels/884471705194627102/884471705194627105)

**Comment by MrTeeXD** [comment]
Awesome! Will test it out. :D
